name: Python lint checks

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: "[flake8]: before"
        run: "./.ci-scripts/flake8_before.sh"

      - name: "[flake8]: run"
        run: "./.ci-scripts/flake8_run.sh"

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yaml') }}

      - name: "[pytest]: before"
        run: "./.ci-scripts/pytest_before.sh"

      - name: "[pytest]: run"
        run: "./.ci-scripts/pytest_run.sh"

      - name: "[pytest]: after"
        run: "./.ci-scripts/pytest_after.sh"
